# Generated by Django 3.2.6 on 2021-09-03 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('MO', 'Mortgage'), ('RE', 'Rent'), ('IN', 'Insurance'), ('TX', 'Taxes'), ('MD', 'Medical'), ('UT', 'Utilities'), ('GR', 'Groceries'), ('GS', 'Gasoline'), ('CR', 'Car'), ('LN', 'Loan'), ('OT', 'Other')], default='MO', max_length=2),
        ),
        migrations.AddField(
            model_name='expense',
            name='user_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='budget.accountinfo'),
        ),
        migrations.AddField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('SL', 'Salary'), ('SO', 'Freelance'), ('JR', 'Dividend'), ('SR', 'Gift'), ('GR', 'Loan'), ('OI', 'Other')], default='SL', max_length=2),
        ),
        migrations.AlterField(
            model_name='income',
            name='user_id',
            field=models.ForeignKey(default='DEFAULT_USER_ID', on_delete=django.db.models.deletion.CASCADE, to='budget.accountinfo'),
        ),
    ]
